# Generated by Django 5.0.3 on 2025-03-07 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threeDapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model3d',
            name='name',
        ),
    ]
