# Generated by Django 5.0.3 on 2025-03-07 17:47

import threeDapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threeDapp', '0002_remove_model3d_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model3d',
            name='file',
            field=models.FileField(upload_to='models/', validators=[threeDapp.models.validate_3d_model_file]),
        ),
    ]
