# Generated by Django 5.0.3 on 2025-03-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threeDapp', '0003_alter_model3d_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='model3d',
            name='format',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='model3d',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
